# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sample_blog',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/sample_blog',
                'lib_path': 'sample_blog'},
  'syms': {'sample_blog.core': {'sample_blog.core.foo': ('core.html#foo', 'sample_blog/core.py')}}}
